"""initial schema

Revision ID: 1d58ea37c51e
Revises: 
Create Date: 2026-08-19 00:09:58.493808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d58ea37c51e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('squad_select', sa.Integer(), nullable=False),
    sa.Column('min_play', sa.Integer(), nullable=False),
    sa.Column('max_play', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('squad_size', sa.Integer(), nullable=False),
    sa.Column('starting_size', sa.Integer(), nullable=False),
    sa.Column('max_players_per_team', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('transfer_cap', sa.Integer(), nullable=False),
    sa.Column('max_extra_free_transfers', sa.Integer(), nullable=False),
    sa.Column('transfer_sell_on_fee', sa.Float(), nullable=False),
    sa.Column('sell_at_purchase_price', sa.Boolean(), nullable=False),
    sa.Column('vice_captain_enabled', sa.Boolean(), nullable=False),
    sa.Column('stats_form_days', sa.Integer(), nullable=False),
    sa.Column('currency_multiplier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_table('scoring_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'stat', 'position_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('strength_overall_home', sa.Integer(), nullable=False),
    sa.Column('strength_overall_away', sa.Integer(), nullable=False),
    sa.Column('strength_attack_home', sa.Integer(), nullable=False),
    sa.Column('strength_attack_away', sa.Integer(), nullable=False),
    sa.Column('strength_defence_home', sa.Integer(), nullable=False),
    sa.Column('strength_defence_away', sa.Integer(), nullable=False),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'fpl_id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('opta_code', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('known_name', sa.String(), nullable=True),
    sa.Column('web_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('team_join_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('can_select', sa.Boolean(), nullable=False),
    sa.Column('can_transact', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_id')
    )
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deadline_time', sa.DateTime(), nullable=False),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('data_checked', sa.Boolean(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('average_score', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('ranked_count', sa.Integer(), nullable=False),
    sa.Column('transfers_made', sa.Integer(), nullable=False),
    sa.Column('highest_scoring_entry', sa.Integer(), nullable=True),
    sa.Column('most_selected_player_id', sa.Integer(), nullable=True),
    sa.Column('most_transferred_in_player_id', sa.Integer(), nullable=True),
    sa.Column('most_captained_player_id', sa.Integer(), nullable=True),
    sa.Column('most_vice_captained_player_id', sa.Integer(), nullable=True),
    sa.Column('top_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['most_captained_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['most_selected_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['most_transferred_in_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['most_vice_captained_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['top_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'number')
    )
    op.create_table('players_seasons_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bps', sa.Integer(), nullable=False),
    sa.Column('influence', sa.Float(), nullable=False),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('threat', sa.Float(), nullable=False),
    sa.Column('ict_index', sa.Float(), nullable=False),
    sa.Column('clearances_blocks_interceptions', sa.Integer(), nullable=False),
    sa.Column('recoveries', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('defensive_contribution', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.Float(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=False),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('selected_by_percent', sa.Float(), nullable=False),
    sa.Column('transfers_in', sa.Integer(), nullable=False),
    sa.Column('transfers_out', sa.Integer(), nullable=False),
    sa.Column('transfers_in_event', sa.Integer(), nullable=False),
    sa.Column('transfers_out_event', sa.Integer(), nullable=False),
    sa.Column('event_points', sa.Integer(), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('ep_next', sa.Float(), nullable=True),
    sa.Column('ep_this', sa.Float(), nullable=True),
    sa.Column('dreamteam_count', sa.Integer(), nullable=False),
    sa.Column('in_dreamteam', sa.Boolean(), nullable=False),
    sa.Column('value_form', sa.Float(), nullable=False),
    sa.Column('value_season', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id')
    )
    op.create_table('chips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('chip_type', sa.String(), nullable=False),
    sa.Column('start_gameweek_id', sa.Integer(), nullable=False),
    sa.Column('end_gameweek_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['start_gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_gameweek_id', sa.Integer(), nullable=False),
    sa.Column('end_gameweek_id', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['start_gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phases')
    op.drop_table('chips')
    op.drop_table('players_seasons_stats')
    op.drop_table('gameweeks')
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('scoring_rules')
    op.drop_table('game_rules')
    op.drop_table('seasons')
    op.drop_table('positions')
    # ### end Alembic commands ###
